name: Actions 😎

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.12f1
        targetPlatform:
          - WebGL

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{matrix.targetPlatform}}-${{matrix.unityVersion}}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          versioning: Semantic
          targetPlatform: ${{matrix.targetPlatform}}

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{matrix.targetPlatform}}
          path: build/${{matrix.targetPlatform}}

      # Deploy
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/${{matrix.targetPlatform}}/${{matrix.targetPlatform}} # The folder the action should deploy.
